hum=int(450)
shake=int(200)
cola=int(100)
sum=int(str(hum+shake+cola))
tax=int(10)
plusTaxOnly=int(str((hum//tax)+(shake//tax)+(cola//tax)))
plusChiponly=round(float(str(sum*0.16)))
allsum=str(sum+plusChiponly+plusTaxOnly)

print('ハンバーガー　　:',hum)
print('シェイク　　　　:',shake)
print('コーラ　　　　　:',cola)
print('合計額（税抜）　:',sum)
print('消費税　　　　　:',plusTaxOnly)
print('チップ　　　　　:',plusChiponly)
print('合計額（税込）　:',allsum)